In [1]:
#membaca/memasukkan library yang dibutuhkan
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
#membaca file dataset

kelapasawit = pd.read_excel('datasetsawit.xlsx')

In [3]:
#menampilkan data yang telah terbaca

kelapasawit

CUACA  HARI  BERATAWAL  BERATAKHIR  KESIMPULAN
0        1     1       3902        3898           1
1        1     6       3984        3950           0
2        0     2       4010        4998           1
3        0     3       4761        4751           1
4        1     4       5985        5970           1
..     ...   ...        ...         ...         ...
187      1     6       6102        6094           0
188      1     6       4812        4801           0
189      0     1       5512        5502           1
190      1     2       5211        5208           1
191      0     2       4987        4986           1

[192 rows x 5 columns]

In [4]:
#menghitung jumlah baris dan kolom pada data

kelapasawit.shape

(192, 5)

In [5]:
#menghitung nilai pada kesimpulan "1 & 0", 1 = pengepulan tepat waktu, 0 = pengepulan ditunda

kelapasawit['KESIMPULAN'].value_counts()

1    126
0     66
Name: KESIMPULAN, dtype: int64

In [6]:
#memisahkan data x = atribut, dan y = label (axis=1 adalah array 2 dimensi terdapat x & y)

x = kelapasawit.drop (columns='KESIMPULAN', axis=1)
y = kelapasawit['KESIMPULAN']

In [7]:
#print untuk menampilkan data x & y

print(x)

     CUACA  HARI  BERATAWAL  BERATAKHIR
0        1     1       3902        3898
1        1     6       3984        3950
2        0     2       4010        4998
3        0     3       4761        4751
4        1     4       5985        5970
..     ...   ...        ...         ...
187      1     6       6102        6094
188      1     6       4812        4801
189      0     1       5512        5502
190      1     2       5211        5208
191      0     2       4987        4986

[192 rows x 4 columns]


In [8]:
print(y)

0      1
1      0
2      1
3      1
4      1
      ..
187    0
188    0
189    1
190    1
191    1
Name: KESIMPULAN, Length: 192, dtype: int64


In [9]:
# untuk membuat rata-rata 0 dan variasi 1
scaler = StandardScaler()

In [10]:
scaler.fit(x)

StandardScaler()

In [11]:
#standarisasi data supaya range nilai sama
standarized_data = scaler.transform(x)

In [12]:
print(standarized_data)

[[ 8.81917104e-01 -1.62814793e+00 -1.47154384e+00 -1.47652578e+00]
 [ 8.81917104e-01  9.94372224e-01 -1.38167822e+00 -1.41879989e+00]
 [-1.13389342e+00 -1.10364390e+00 -1.35318424e+00 -2.55401210e-01]
 [-1.13389342e+00 -5.79139867e-01 -5.30146661e-01 -5.29599181e-01]
 [ 8.81917104e-01 -5.46358365e-02  8.11262124e-01  8.23628862e-01]
 [ 8.81917104e-01 -5.46358365e-02 -1.79703274e+00 -1.80733952e+00]
 [ 8.81917104e-01  9.94372224e-01 -4.70966862e-01 -4.75203632e-01]
 [ 8.81917104e-01  9.94372224e-01 -5.23571128e-01 -5.30709294e-01]
 [-1.13389342e+00 -5.79139867e-01  8.05782513e-01  8.21408635e-01]
 [ 8.81917104e-01 -5.79139867e-01  7.72904847e-01  7.95876031e-01]
 [ 8.81917104e-01 -5.79139867e-01 -5.96997916e-01 -6.37280165e-01]
 [ 8.81917104e-01 -5.79139867e-01 -1.62606887e+00 -1.63971242e+00]
 [-1.13389342e+00 -5.46358365e-02 -2.84660086e-01 -2.86484380e-01]
 [-1.13389342e+00  1.51887625e+00 -1.36414346e+00 -1.38549649e+00]
 [ 8.81917104e-01  9.94372224e-01  5.86598071e-01  6.10487119e

In [13]:
x = standarized_data
y = kelapasawit['KESIMPULAN']

In [14]:
print(x)
print(y)

[[ 8.81917104e-01 -1.62814793e+00 -1.47154384e+00 -1.47652578e+00]
 [ 8.81917104e-01  9.94372224e-01 -1.38167822e+00 -1.41879989e+00]
 [-1.13389342e+00 -1.10364390e+00 -1.35318424e+00 -2.55401210e-01]
 [-1.13389342e+00 -5.79139867e-01 -5.30146661e-01 -5.29599181e-01]
 [ 8.81917104e-01 -5.46358365e-02  8.11262124e-01  8.23628862e-01]
 [ 8.81917104e-01 -5.46358365e-02 -1.79703274e+00 -1.80733952e+00]
 [ 8.81917104e-01  9.94372224e-01 -4.70966862e-01 -4.75203632e-01]
 [ 8.81917104e-01  9.94372224e-01 -5.23571128e-01 -5.30709294e-01]
 [-1.13389342e+00 -5.79139867e-01  8.05782513e-01  8.21408635e-01]
 [ 8.81917104e-01 -5.79139867e-01  7.72904847e-01  7.95876031e-01]
 [ 8.81917104e-01 -5.79139867e-01 -5.96997916e-01 -6.37280165e-01]
 [ 8.81917104e-01 -5.79139867e-01 -1.62606887e+00 -1.63971242e+00]
 [-1.13389342e+00 -5.46358365e-02 -2.84660086e-01 -2.86484380e-01]
 [-1.13389342e+00  1.51887625e+00 -1.36414346e+00 -1.38549649e+00]
 [ 8.81917104e-01  9.94372224e-01  5.86598071e-01  6.10487119e

In [15]:
#spliting data (memecah data training = 80% dan testing 20%)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, stratify=y, random_state=2)

In [16]:
print(x.shape, x_train.shape, x_test.shape)

(192, 4) (153, 4) (39, 4)


In [17]:
#untuk data yang dapat dipisahkan secara linear, 
#dataset dapat diklasifikasi menjadi dua kelas dengan menggunakan sebuah garis lurus tunggal

classifier = svm.SVC(kernel='linear')

In [18]:
classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [19]:
#menguji akurasi prediksi data training

x_train_prediction = classifier.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [20]:
print('akurasi data training adalah = ', training_data_accuracy)

akurasi data training adalah =  0.6601307189542484


In [21]:
#menguji akurasi prediksi data testing

x_test_prediction = classifier.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [22]:
print('akurasi data testing adalah = ', test_data_accuracy)

akurasi data testing adalah =  0.6666666666666666


In [ ]:
#membuat form input data

CUACA = eval(input ('input nilai cuaca ='))
print(CUACA)

HARI = eval(input('input nilai hari ='))
print(HARI)

BERATAWAL = eval(input ('input nilai berat awal ='))
print(BERATAWAL)

BERATAKHIR = eval(input('input nilai berat akhir ='))
print(BERATAKHIR)

In [5]:
type (CUACA)

int

In [6]:
#melakukan prediksi dan menampilkan hasil prediksi
input_data = (CUACA, HARI, BERATAWAL, BERATAKHIR)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

#index ke [0] karena label yang diambil berada di index 0 karena hanya ada 1 label  
if (prediction[0] == 0):
    print('pengepulan kelapa sawit ditunda')
else :
    print('pengepulan kelapa sawit tepat waktu')

NameError: name 'np' is not defined

In [26]:
#library untuk menyimpan sebuah file
import pickle

In [27]:
#menyimpan dan memberi nama file
filename = 'kelapasawit_model.sav'
pickle.dump(classifier, open(filename,'wb'))